In [107]:
import pandas as pd
from unidecode import unidecode

In [108]:
data = pd.read_csv('resultados_finales.csv')
data['AÑO'] = '2009-2023'
dataq1 = pd.read_excel('tasas_quinquenio1.xlsx')
dataq2 = pd.read_excel('tasas_quinquenio2.xlsx')
dataq3 = pd.read_excel('tasas_quinquenio3.xlsx')

In [109]:
dataq1

,DPNOM,FALLECIDAS,TOTAL_MUJERES,Tasa_Mortalidad_Cruda,TAE,MUERTES_ESPERADAS,SMR
0,ANTIOQUIA,1811,5568764,32.520681,39.396529,1921.195445,94.264225
1,ARAUCA,41,144028,28.466687,30.798612,49.688932,82.513345
2,ARCHIPIÉLAGO DE SAN ANDRÉS,11,56899,19.332501,30.145098,19.629868,56.037057
3,ATLÁNTICO,737,1957050,37.658721,44.531080,675.172362,109.157312
4,BOLÍVAR,379,1509793,25.102779,28.353060,520.870957,72.762744
5,BOYACÁ,208,1133291,18.353627,19.406545,390.979669,53.199697
6,CALDAS,311,1037805,29.967094,34.687135,358.037482,86.862414
7,CAQUETÁ,58,248410,23.348496,26.127491,85.700195,67.677792
8,CASANARE,34,225464,15.080013,18.376796,77.783941,43.710822
9,CAUCA,173,1086222,15.926763,17.473279,374.741102,46.165206
10,CESAR,160,700351,22.845687,27.380201,241.617557,66.220353
11,CHOCÓ,15,288324,5.202481,5.423441,99.470323,15.079875
12,CUNDINAMARCA,2776,2007275,138.296945,159.436093,692.499733,400.866580
13,CÓRDOBA,245,1288293,19.017413,20.861202,444.454576,55.123743
14,GRUPO AMAZONA,8,138461,5.777800,7.513515,47.768345,16.747492
15,HUILA,247,797184,30.984064,35.977801,275.024452,89.810196
16,LA GUAJIRA,46,442792,10.388625,12.606886,152.761003,30.112397
17,MAGDALENA,210,881151,23.832465,26.593313,303.992643,69.080619
18,META,168,672066,24.997545,30.198248,231.859374,72.457713
19,NARIÑO,216,1350159,15.998116,18.166142,465.798033,46.372029
20,NORTE DE SANTANDER,288,1149877,25.046157,27.828805,396.701755,72.598620
21,PUTUMAYO,15,189700,7.907222,9.116024,65.445542,22.919820
22,QUINDIO,196,561099,34.931447,40.779804,193.576320,101.252054
23,RISARALDA,317,927142,34.191095,39.108586,319.859306,99.106074
24,SANTANDER,520,1866849,27.854422,31.057173,644.053473,80.738638
25,SUCRE,133,654632,20.316758,21.796710,225.844733,58.890016
26,TOLIMA,327,1247051,26.221863,28.428803,430.226294,76.006512
27,VALLE DEL CAUCA,1512,4223965,35.795751,41.150608,1457.246584,103.757320

In [110]:
data.rename(columns={'Nombre_Departamento_Def': 'DPNOM'}, inplace=True)

In [111]:
dataq1['DPNOM'] = dataq1['DPNOM'].apply(unidecode)
reemplazo = {'ARCHIPIELAGO DE SAN ANDRES': 'SAN ANDRES PROVIDENCIA Y SANTA CATALINA', 'NARINO': 'NARIÑO'}
dataq1['DPNOM'] = dataq1['DPNOM'].replace(reemplazo)
dataq1['AÑO'] = '2009-2013'
dataq2['DPNOM'] = dataq2['DPNOM'].apply(unidecode)
dataq2['DPNOM'] = dataq2['DPNOM'].replace(reemplazo)
dataq2['AÑO'] = '2014-2018'
dataq3['DPNOM'] = dataq3['DPNOM'].apply(unidecode)
dataq3['DPNOM'] = dataq3['DPNOM'].replace(reemplazo)
dataq3['AÑO'] = '2019-2023'

In [112]:
data_f = pd.concat([data,dataq1, dataq2, dataq3], ignore_index=True)
data_f

,DPNOM,TOTAL_MUJERES,FALLECIDAS,Tasa_Mortalidad_Cruda,TAE,MUERTES_ESPERADAS,SMR,beta_1,CPPA,porcentaje_inestabilidad,AÑO
0,ANTIOQUIA,19011651,6185,32.532682,38.466253,7108.466479,87.008921,-0.011208,-1.114561,0.0,2009-2023
1,ARAUCA,543874,137,25.189658,30.488575,203.354780,67.369943,0.003720,0.372730,0.0,2009-2023
2,SAN ANDRES PROVIDENCIA Y SANTA CATALINA,189144,30,15.860931,26.424814,70.721043,42.420189,-0.015796,-1.567236,100.0,2009-2023
3,ATLANTICO,6773319,3122,46.092617,54.323739,2532.547598,123.275077,0.008062,0.809453,0.0,2009-2023
4,BOLIVAR,5135499,1588,30.922019,35.703283,1920.165823,82.701191,0.001754,0.175564,0.0,2009-2023
...,...,...,...,...,...,...,...,...,...,...,...
107,RISARALDA,1130316,469,41.492821,44.216005,443.075469,105.851042,NaN,NaN,NaN,2019-2023
108,SANTANDER,2440944,931,38.140982,41.835260,956.831901,97.300268,NaN,NaN,NaN,2019-2023
109,SUCRE,853874,235,27.521625,31.145821,334.712260,70.209559,NaN,NaN,NaN,2019-2023
110,TOLIMA,1481130,458,30.922336,32.801461,580.591949,78.885007,NaN,NaN,NaN,2019-2023
111,VALLE DEL CAUCA,5064100,2162,42.692680,45.609817,1985.089551,108.911963,NaN,NaN,NaN,2019-2023

In [ ]:
dataq1.rename(columns={'Tasa_Mortalidad_Cruda': 'TMC Q1'}, inplace=True)
dataq1.rename(columns={'TAE': 'TAE Q1'}, inplace=True)
dataq1.rename(columns={'SMR': 'SMR Q1'}, inplace=True)
dataq1.rename(columns={'TOTAL_MUJERES': 'TOTAL_MUJERES Q1'}, inplace=True)
dataq1.rename(columns={'FALLECIDAS': 'FALLECIDAS Q1'}, inplace=True)
dataq1.rename(columns={'MUERTES_ESPERADAS': 'MUERTES_ESPERADAS Q1'}, inplace=True)

dataq2.rename(columns={'Tasa_Mortalidad_Cruda': 'TMC Q2'}, inplace=True)
dataq2.rename(columns={'TAE': 'TAE Q2'}, inplace=True)
dataq2.rename(columns={'SMR': 'SMR Q2'}, inplace=True)
dataq2.rename(columns={'TOTAL_MUJERES': 'TOTAL_MUJERES Q2'}, inplace=True)
dataq2.rename(columns={'FALLECIDAS': 'FALLECIDAS Q2'}, inplace=True)
dataq2.rename(columns={'MUERTES_ESPERADAS': 'MUERTES_ESPERADAS Q2'}, inplace=True)


dataq3.rename(columns={'Tasa_Mortalidad_Cruda': 'TMC Q3'}, inplace=True)
dataq3.rename(columns={'TAE': 'TAE Q3'}, inplace=True)
dataq3.rename(columns={'SMR': 'SMR Q3'}, inplace=True)
dataq3.rename(columns={'TOTAL_MUJERES': 'TOTAL_MUJERES Q3'}, inplace=True)
dataq3.rename(columns={'FALLECIDAS': 'FALLECIDAS Q3'}, inplace=True)
dataq3.rename(columns={'MUERTES_ESPERADAS': 'MUERTES_ESPERADAS Q3'}, inplace=True)

In [84]:
data_final = pd.merge(data, dataq1, left_on='Nombre_Departamento_Def', right_on='DPNOM', how='left')
data_final.drop(columns=['DPNOM'], inplace=True)
data_final = pd.merge(data_final, dataq2, left_on='Nombre_Departamento_Def', right_on='DPNOM', how='left')
data_final.drop(columns=['DPNOM'], inplace=True)
data_final = pd.merge(data_final, dataq3, left_on='Nombre_Departamento_Def', right_on='DPNOM', how='left')

In [85]:
data_final.to_excel('resultados_finales_con_tasas.xlsx', index=False)

In [113]:
data_f.to_excel('re.xlsx', index=False)